### ISSUE TITLE
Upgrade the metrics libraries

### ISSUE THREAD

**Issue by lrabbit** [spotify/semantic-metrics#26]
The `metrics` libraries (`com.codahale.metrics`:`metrics-core`:`3.0.2` and `com.codahale.metrics`:`metrics-jvm`:`3.0.2`) are more than 4 years old and are not maintained anymore. Also, their `groupId` has changed since then (it is now set to `io.dropwizard.metrics`). For these reasons, I think they must be upgraded to more recent versions. I will create a PR with the required changes.

**Comment by lrabbit** [comment]
Oh, this lib has to be java 7 compatible... Do you think a java 8+ version of this lib could be done ?

**Comment by dmichel1** [comment]
@lrabbit I think its time to drop support for java 7 in the latest release of `semantic-metrics`

We can do something similar to [folsom](https://github.com/spotify/folsom#java-7-usage) and call out how to specifically use it with java 7. 

I'm not very familiar with the differences from codehale 3.x -> metrics 4.x but looks like its mostly a drop in replacement... https://github.com/dropwizard/metrics#version-4xx-javadoc

\cc @hexedpackets

**Comment by lrabbit** [comment]
@dmichel1 👍.  That will allow us to clean things up a bit in hermes-java and everywhere this lib is used... What's the plan then ?

**Comment by dmichel1** [comment]
@lrabbit will also need to update Apollo. Can you ping me on slack and we can discuss this some more...

**Comment by mattnworb** [comment]
Kind of implicit in this PR is that users of semantic-metrics-* would also need to adapt to using com.codahale.metrics v4 as well. I don't think the type of change in the upstream library that that snippet refers to can be solved within this repo.

**Comment by lrabbit** [comment]
ouch

**Comment by lrabbit** [comment]
Closing since this issue has been resolved by PR #30
